var Firebase = require("firebase");

var rootRef = new Firebase('https://docs-examples.firebaseio.com/web/data');
console.log(rootRef.child('users/mchen/name'));

var ref = new Firebase("https://recipeez.firebaseio.com/web/data");
var usersRef = ref.child("users");
usersRef.set({
  alanisawesome: {
    date_of_birth: "June 23, 1912",
    full_name: "Alan Turing"
  },
  gracehop: {
    date_of_birth: "December 9, 1906",
    full_name: "Grace Hopper"
  }
});

var hopperRef = usersRef.child("gracehop");
hopperRef.update({
  "nickname": "Amazing Grace"
});

usersRef.update({
  "alanisawesome/nickname": "Alan The Machine",
  "gracehop/nickname": "Amazing Grace"
});

var postsRef = ref.child("posts");
var newPostRef = postsRef.push();
newPostRef.set({
author: "gracehop",
title: "Announcing COBOL, a New Programming Language"
});
// we can also chain the two calls together
postsRef.push().set({
author: "alanisawesome",
title: "The Turing Machine"
});

postsRef.push({
	author: "gracehop",
	title: "Hello World!"
});

// Generate a reference to a new location and add some data using push()
var newPostRef = postsRef.push({
	author: "gracehop",
	title: "Goodbye Yahoo"
});
// Get the unique ID generated by push()
var postID = newPostRef.key();
console.log('postID: ' + postID);